sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

before_script:
  - mvn -f demo_tictak/pom.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn -f demo_tictak/pom.xml test -B
  - docker build -t almedvedev/tictactoe-demo demo_tictak/.

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push almedvedev/tictactoe-demo;
    fi