sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x demo_tictak/mvnw 
  - demo_tictak/mvnw -install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

install:
  - demo_tictak/mvnw test -B
  - docker build -t tic-tac-toe demo_tictak/.