sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

before_script:
  - mvn -f demo_tictak/pom.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn -f demo_tictak/pom.xml test -B
  - docker build -t tic-tac-toe demo_tictak/.